# Generated by Django 5.2 on 2025-04-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=30)),
                ('releaseDate', models.DateField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
